HOSTS:
  ubuntu1204:
    roles:
      - nodes
      - ubuntu12
    platform: ubuntu-1204-amd64
    image: ubuntu:12.04
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y iptables sudo'
CONFIG:
  type: foss
  log_level: notice
