---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    firewall: https://github.com/puppetlabs/puppetlabs-firewall.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
    mount_core: https://github.com/puppetlabs/puppetlabs-mount_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    translate: https://github.com/puppetlabs/puppetlabs-translate.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
