fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
