---
AllCops:
  Exclude:
    - 'vagrant/modules/*/Gemfile'
    - 'vagrant/modules/*/Rakefile'
    - 'vagrant/modules/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
