---
version: 2
jobs:
  build:
    docker:
      - environment:
          PUPPET_VERSION: "~> 3.8"
          STRICT_VARIABLES: true
        image: "ruby:2.1.9"
    steps:
      - checkout
      - restore_cache:
          keys:
            - "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
            - "projectname-{{ .Branch }}"
            - projectname-master
      - run:
          command: "bundle install --without development acceptance --path vendor/bundle"
          name: "Bundle Install"
      - run:
          command: "bundle clean --force"
          name: "Bundle Cleanup"
      - save_cache:
          key: "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
          paths:
            - vendor/bundle
      - run:
          command: "bundle clean --force"
          name: "Bundle Cleanup"
