---
jobs:
  build:
    docker:
      -
        environment:
          PUPPET_VERSION: "~> 3.8"
          STRICT_VARIABLES: true
        image: "ruby:2.1.9"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
            - "projectname-{{ .Branch }}"
            - projectname-master
      -
        run:
          command: "bundle install --without development acceptance --path vendor/bundle"
          name: "Bundle Install"
      -
        run:
          command: "bundle clean --force"
          name: "Bundle Cleanup"
      -
        save_cache:
          key: "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
          paths:
            - vendor/bundle
      -
        run:
          command: "bundle clean --force"
          name: "Bundle Cleanup"
      -
        run:
          command: "bundle exec puppet --version"
          name: "Show Puppet version"
      -
        run:
          command: "bundle exec travis-lint"
          name: "TravisCI Lint"
      -
        run:
          command: "bundle exec rake metadata_lint"
          name: "Puppet Metadata Lint"
      -
        run:
          command: "bundle exec rake lint"
          name: "Puppet Lint"
      -
        run:
          command: "bundle exec rake validate"
          name: "Validate the Puppet code"
      -
        run:
          command: "bundle exec rake spec SPEC_OPTS=\"--format documentation --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/puppet.xml\""
          name: "Spec tests"
      -
        deploy:
          name: Deploy from master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a -z "${RUN_NIGHTLY_BUILD}" ]; then
              git config --global user.email "info@locp.co.uk"
              git config --global user.name "CircleCI"
              bundle exec rake strings:gh_pages:update
              bundle exec rake deploy
            fi
    working_directory: ~/cassandra
version: 2
